#!/bin/bash
cd `dirname $0`

if test -e /proc/
then {
    export CPUCOUNT=$(grep -c ^processor /proc/cpuinfo)
}
else {
    export CPUCOUNT=$(sysctl -n hw.ncpu)
    export TOOLSET="toolset=clang"
    export DYLD_LIBRARY_PATH=../dist/lib
    export LANG=C
}
fi

if ../bjam -j$CPUCOUNT $TOOLSET $(../python.opts.sh) $*
then {
    echo fost-aws $* OK
    exit 0
} else {
    exit 1
}
fi
